// Turns a generated HTML document into a shippable project:
// PWA (manifest + service worker + icons) and a Capacitor shell for iOS/Android.

export interface AppMeta {
  name: string;
  shortName: string;
  slug: string;
  themeColor: string;
  backgroundColor: string;
  description: string;
}

/** Pulls the HTML document out of a (possibly partial) model response. */
export function extractHtml(raw: string): string {
  const fenced = raw.match(/```(?:html|HTML)?[^\n]*\n([\s\S]*?)(?:```|$)/);
  let html = fenced ? fenced[1] : raw;
  const start = html.search(/<!doctype html|<html[\s>]/i);
  if (start > 0) html = html.slice(start);
  const end = html.search(/<\/html>/i);
  if (end !== -1) html = html.slice(0, end + "</html>".length);
  return html.trim();
}

export function isCompleteHtml(html: string): boolean {
  return /<\/html>\s*$/i.test(html.trim());
}

export function slugify(s: string): string {
  return (
    s
      .toLowerCase()
      .normalize("NFKD")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "app"
  );
}

const HEX = /^#(?:[0-9a-f]{3}){1,2}$/i;

export function deriveMeta(html: string, appName?: string): AppMeta {
  const title = html.match(/<title[^>]*>([^<]*)<\/title>/i)?.[1]?.trim();
  const theme = html.match(/<meta[^>]+name=["']theme-color["'][^>]*content=["']([^"']+)["']/i)?.[1]
    ?? html.match(/<meta[^>]+content=["']([^"']+)["'][^>]*name=["']theme-color["']/i)?.[1];
  const desc = html.match(/<meta[^>]+name=["']description["'][^>]*content=["']([^"']*)["']/i)?.[1];
  const name = appName?.trim() || title?.split(/\s[|–—-]\s/)[0]?.trim() || "My App";
  const themeColor = theme && HEX.test(theme.trim()) ? theme.trim() : "#6d5efc";
  return {
    name,
    shortName: name.length > 12 ? name.split(/\s+/)[0].slice(0, 12) : name,
    slug: slugify(name),
    themeColor,
    backgroundColor: "#ffffff",
    description: desc ?? `${name} — built with mobile.do`,
  };
}

function escapeXml(s: string): string {
  return s.replace(/[<>&"']/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&apos;" })[c]!);
}

export function iconSvg(meta: AppMeta): string {
  const letter = escapeXml((meta.name.match(/[\p{L}\p{N}]/u)?.[0] ?? "A").toUpperCase());
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="${meta.themeColor}"/><stop offset="1" stop-color="${meta.themeColor}" stop-opacity=".72"/>
  </linearGradient></defs>
  <rect width="512" height="512" rx="112" fill="url(#g)"/>
  <text x="256" y="256" dy=".35em" text-anchor="middle" font-family="system-ui,-apple-system,Segoe UI,Roboto,sans-serif" font-size="280" font-weight="700" fill="#fff">${letter}</text>
</svg>`;
}

export function manifest(meta: AppMeta): string {
  return JSON.stringify(
    {
      name: meta.name,
      short_name: meta.shortName,
      description: meta.description,
      start_url: "./",
      scope: "./",
      display: "standalone",
      orientation: "portrait",
      theme_color: meta.themeColor,
      background_color: meta.backgroundColor,
      icons: [
        { src: "icons/icon-192.png", sizes: "192x192", type: "image/png" },
        { src: "icons/icon-512.png", sizes: "512x512", type: "image/png" },
        { src: "icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        { src: "icons/icon.svg", sizes: "any", type: "image/svg+xml" },
      ],
    },
    null,
    2,
  );
}

export function serviceWorker(meta: AppMeta, version: string | number = Date.now()): string {
  return `// Offline support generated by mobile.do
const CACHE = "${meta.slug}-v${version}";
const SHELL = ["./", "./index.html", "./manifest.webmanifest", "./icons/icon.svg", "./icons/icon-192.png", "./icons/icon-512.png"];

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  if (req.mode === "navigate") {
    e.respondWith(fetch(req).catch(() => caches.match("./index.html")));
    return;
  }
  e.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok && (res.type === "basic" || res.type === "cors")) {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
      }
      return res;
    }).catch(() => hit)),
  );
});
`;
}

/** Adds manifest, icons and service-worker registration to the generated document. */
export function injectPwa(html: string, meta: AppMeta): string {
  let out = html;
  const head = [
    !/rel=["']manifest["']/i.test(out) && `<link rel="manifest" href="manifest.webmanifest">`,
    !/rel=["']icon["']/i.test(out) && `<link rel="icon" href="icons/icon.svg" type="image/svg+xml">`,
    !/apple-touch-icon/i.test(out) && `<link rel="apple-touch-icon" href="icons/icon-192.png">`,
    !/apple-mobile-web-app-capable/i.test(out) && `<meta name="apple-mobile-web-app-capable" content="yes">`,
    !/mobile-web-app-capable"/i.test(out) && `<meta name="mobile-web-app-capable" content="yes">`,
    !/theme-color/i.test(out) && `<meta name="theme-color" content="${meta.themeColor}">`,
  ].filter(Boolean).join("\n");
  const sw = `<script>if("serviceWorker"in navigator&&location.protocol.startsWith("http"))addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));</script>`;
  out = /<\/head>/i.test(out) ? out.replace(/<\/head>/i, `${head}\n</head>`) : `${head}\n${out}`;
  out = /<\/body>/i.test(out) ? out.replace(/<\/body>(?![\s\S]*<\/body>)/i, `${sw}\n</body>`) : `${out}\n${sw}`;
  return out;
}

export function capacitorConfig(meta: AppMeta): string {
  return JSON.stringify(
    {
      appId: `app.mobiledo.${meta.slug.replace(/-/g, "") || "app"}`,
      appName: meta.name,
      webDir: "www",
      backgroundColor: meta.backgroundColor,
    },
    null,
    2,
  );
}

export function projectPackageJson(meta: AppMeta): string {
  return JSON.stringify(
    {
      name: meta.slug,
      version: "1.0.0",
      private: true,
      description: meta.description,
      scripts: {
        start: "npx --yes serve www",
        "add:android": "npx cap add android",
        "add:ios": "npx cap add ios",
        sync: "npx cap sync",
        android: "npx cap sync android && npx cap open android",
        ios: "npx cap sync ios && npx cap open ios",
      },
      dependencies: {
        "@capacitor/android": "^8.5.0",
        "@capacitor/core": "^8.5.0",
        "@capacitor/ios": "^8.5.0",
      },
      devDependencies: { "@capacitor/cli": "^8.5.0" },
    },
    null,
    2,
  );
}

export function projectReadme(meta: AppMeta, source: string): string {
  return `# ${meta.name}

Generated by **mobile.do** from ${source}.

## Ship it as a mobile website / PWA
Deploy the \`www/\` folder to any static host (Vercel, Netlify, Cloudflare Pages, GitHub Pages).
It's installable ("Add to Home Screen") and works offline via \`sw.js\`.

\`\`\`bash
npm start            # preview locally at http://localhost:3000
npx vercel www       # or drag www/ into Netlify Drop
\`\`\`

## Ship it as a native iOS / Android app (Capacitor)
\`\`\`bash
npm install
npm run add:android  # once — requires Android Studio
npm run add:ios      # once — requires Xcode on macOS
npm run android      # build, run, then publish to Google Play
npm run ios          # build, run, then publish to the App Store
\`\`\`
Replace \`www/icons/*\` with production artwork before store submission.

## Keep iterating with Claude Code
\`\`\`bash
claude "Read CLAUDE.md, then improve the app in www/index.html"
\`\`\`
`;
}

export function claudeMd(meta: AppMeta, brief: string): string {
  return `# ${meta.name} — project guide for Claude Code

This is a mobile-first web app generated by mobile.do, packaged as a PWA and a Capacitor native shell.

## Layout
- \`www/index.html\` — the entire app (HTML + CSS + JS, no build step). Edit this.
- \`www/manifest.webmanifest\`, \`www/sw.js\`, \`www/icons/\` — PWA plumbing; bump the cache name in sw.js when shipping.
- \`capacitor.config.json\` — native app id/name; \`webDir\` is \`www\`.
${brief.includes("<source_site>") ? "- `site.json` — structured digest of the source website (content, brand palette, images).\n" : ""}
## Rules
- Keep it a single self-contained \`www/index.html\`; no frameworks or CDNs unless asked.
- Mobile quality bar: safe-area insets, ≥44px touch targets, bottom tab bar + hash routing, light/dark themes,
  no horizontal scroll at 320px, accessible labels, localStorage wrapped in try/catch.
- Verify changes by serving \`www/\` (\`npm start\`) and checking at 390×844.

## Original brief
${brief}
`;
}
